### ISSUE TITLE
Join Podcasting 2.0!

### ISSUE THREAD

**Issue by MerryOscar** [gazhayes/nostrovia.org#2]
Hey guys - looking forward to listening to this!

You should join Fountain / Podcasting 2.0 so people can stream you sats / send you boosts - https://fountain.fm/podcasters

Currently exploring how we can integrate nostr into Fountain's social features so maybe there will be something to share on that soon too... :)

**Comment by gsovereignty** [comment]
Thanks @MerryOscar! I really like the idea of fountain, I think I heard about it from Marty or someone on citadel dispatch.

### Some feedback
I tried to claim nostrovia, but had 2 issues:
1. The email that is sent to verify a claim is badly formatted:
https://user-images.githubusercontent.com/8143945/211257480-adcbc7a8-8fba-42f8-87b9-6221c5f64d6a.mov

2. Internal server error when going to the link

<img width="633" alt="Screenshot 2023-01-09 at 3 15 40 PM" src="https://user-images.githubusercontent.com/8143945/211257568-3515ff1b-43f1-4092-a549-9b791315e726.png">

**Comment by MerryOscar** [comment]
Oh sorry about that!

The error should be fixed now. What email client are you using?

**Comment by gsovereignty** [comment]
Awesome! done.

@MerryOscar I'm using protonmail

The email is still weird, but the verification now works.

Join the telegram group: http://t.me/nostroviadispatch to hook up a time to come on the show and the three of us can brainstorm live about integrating fountain and nostr

**Comment by MerryOscar** [comment]
🎉 🤙 https://fountain.fm/show/EHr7oroKVhkIAWNTGGRn
